### ISSUE TITLE
gapminder in xaringan_reveal_parentheses_balanced.R

### ISSUE THREAD

**Issue by novica** [EvaMaeRey/little_flipbooks_library#3]
Hi. 

I am not sure if this is really an issue or more of a question, but here it goes.
I wanted to use your tidy tuesday flipbook template and noticed some problems.

As far as I can see the .Rmd  talks about `gapminder` but actually uses `nobel` data. So I guess this should be fixed?  But also without any reference to `gapminder` in the .Rmd there is some guessing that actually we need to install `gapminder` (assuming not everybody has that installed already) before any knitting is possible because `xaringan_reveal_parentheses_balanced.R` loads that regardless.

**Comment by EvaMaeRey** [comment]
I am definitely happy to have feedback such as this!  Thank you! Please let me know if you come across more issues as you work through your project.  You point out an interesting thing about gapminder package in the R script.  Perhaps I should change the example to something in base R so there is not this additional dependency.

**Comment by novica** [comment]
Yes. I think it's better not to have the basic template depend on additional packages.

**Comment by EvaMaeRey** [comment]
I've addressed the mistakes that you've mentioned (changing gapminder to nobel).  And have it in mind to change the source code examples to something other than gapminder.

**Comment by EvaMaeRey** [comment]
Does this clarify things? 

![image](https://user-images.githubusercontent.com/10491910/65064260-4ed00980-d93d-11e9-9239-e730866958d6.png)

**Comment by novica** [comment]
Thank you. This clarifies things.

**Comment by novica** [comment]
I think the issue remains in `xaringan_reveal_parentheses_balanced.R`. I just tried to knit the updated `tidytuesday_minimal_example.Rmd` without having any libraries loaded and it failed with `Error in library(gapminder) : there is no package called 'gapminder'`. So the question is: is `gapminder` really necessary in `xaringan_reveal_parentheses_balanced.R`. If yes I would update the minimal example with a slide saying that in order to see the presentation you need to `install.packages('gapminder`)`. If no, then remove that code form the R script.

Or instead of `"gapminder %>%             # the data  #REVEAL`  maybe use some dataset that is available by default.
